# Banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/antibankfraud
spring.datasource.username=postgres
spring.datasource.password=voltaaotempo

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=chave-secreta-super-longa-para-o-projeto-antibankfraud-2024
jwt.expiration=86400000

# Email para OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
spring.mail.password=sua_senha_de_app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.name=admin
spring.security.user.password=admin